### ISSUE TITLE
cgo panic, Go 1.6 behaviour

### ISSUE THREAD

**Issue by notnot** [gordonklaus/portaudio#12]
After upgrading to Go 1.6 i get a panic:

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 5 [running]:
panic(0x42157c0, 0xc8200e6050)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
code.google.com/p/portaudio-go/portaudio._cgoCheckPointer1(0x4194520, 0xc8200ec000, 0x0, 0x0, 0x0, 0x4184060)
	??:0 +0x4d
code.google.com/p/portaudio-go/portaudio.OpenStream(0x0, 0x0, 0x0, 0xc820016240, 0x1, 0xd9fb92, 0x40e5888000000000, 0x400, 0x0, 0xc8200e6000, ...)
	/Users/jpad/gocode/extern/src/code.google.com/p/portaudio-go/portaudio/portaudio.go:502 +0x3d1
...

I think this caused by the stricter 1.6 rules about Go/C memory sharing? Is there a way around it?

**Comment by notnot** [comment]
Ah, browsing the old issues i found out that this issue has been fixed already. All i needed to to was update my portaudio package, thanks!
