### ISSUE TITLE
Example `play.go` not working correctly

### ISSUE THREAD

**Issue by the-technat** [gordonklaus/portaudio#53]
Hello there!

I stumbled over your module when looking for a library to interact with sound in go. So far so good, I got some things working with the help of your examples. However when I try to use the [play.go](https://github.com/gordonklaus/portaudio/blob/master/examples/play.go) example I can hear that the sound starts playing but then suddenly interrupts with the following error:

```bash
Playing.  Press Ctrl-C to stop.
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
panic: unexpected EOF

goroutine 1 [running]:
main.chk(...)
	/tmp/gugus/main.go:124
main.main()
	/tmp/gugus/main.go:77 +0x870
exit status 2
```

Using debugging tools I can see that [this line](https://github.com/gordonklaus/portaudio/blob/master/examples/play.go#L73) produces the error when `remaining` is about 4500 (started by 8000 or so).
Interestingly enough the [mp3.go](https://github.com/gordonklaus/portaudio/blob/master/examples/mp3.go) example works fine.

I'm not a sound pro, so the problem could easily by on my side. But maybe you can help me out with that?

Some debugging information:
- go version: `go version go1.19.1 linux/amd64`
- portaudio package version `1:19.7.0-1`
- OS: Arch Linux 
- Sound file: https://kdrive.infomaniak.com/app/share/571419/395fb0cf-3efb-46dd-a938-ab41da39aa60 (.aiff format)

**Comment by the-technat** [comment]
I just observed that it works with other files. I assume that I just need to add some checks in what format the file is...
